//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First_CURD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaTbl
    {
        public long AreaId { get; set; }
        public string AreaName { get; set; }
        public string CityName { get; set; }
        public long DeptId { get; set; }
    
        public virtual DeptTbl DeptTbl { get; set; }
    }
}
