// <auto-generated />
using COREExamUsing5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COREExamUsing5.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COREExamUsing5.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.ToTable("EmpTbl");
                });

            modelBuilder.Entity("COREExamUsing5.Models.EmpSalary", b =>
                {
                    b.Property<long>("EmpSalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("EmpID")
                        .HasColumnType("bigint");

                    b.HasKey("EmpSalaryID");

                    b.HasIndex("EmpID")
                        .IsUnique();

                    b.ToTable("EmpSalTbl");
                });

            modelBuilder.Entity("COREExamUsing5.Models.SalaryAddtion", b =>
                {
                    b.Property<long>("SalaryAdditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AdditionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdditionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmpID")
                        .HasColumnType("bigint");

                    b.HasKey("SalaryAdditionID");

                    b.HasIndex("EmpID")
                        .IsUnique();

                    b.ToTable("SalAddTbl");
                });

            modelBuilder.Entity("COREExamUsing5.Models.SalaryDeduction", b =>
                {
                    b.Property<long>("SalaryDeductionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeductionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmpID")
                        .HasColumnType("bigint");

                    b.HasKey("SalaryDeductionID");

                    b.HasIndex("EmpID")
                        .IsUnique();

                    b.ToTable("SalDedTbl");
                });

            modelBuilder.Entity("COREExamUsing5.Models.EmpSalary", b =>
                {
                    b.HasOne("COREExamUsing5.Models.Emp", "Emp")
                        .WithOne("EmpSalary")
                        .HasForeignKey("COREExamUsing5.Models.EmpSalary", "EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("COREExamUsing5.Models.SalaryAddtion", b =>
                {
                    b.HasOne("COREExamUsing5.Models.Emp", "Emp")
                        .WithOne("SalaryAddtion")
                        .HasForeignKey("COREExamUsing5.Models.SalaryAddtion", "EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("COREExamUsing5.Models.SalaryDeduction", b =>
                {
                    b.HasOne("COREExamUsing5.Models.Emp", "Emp")
                        .WithOne("SalaryDeduction")
                        .HasForeignKey("COREExamUsing5.Models.SalaryDeduction", "EmpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("COREExamUsing5.Models.Emp", b =>
                {
                    b.Navigation("EmpSalary");

                    b.Navigation("SalaryAddtion");

                    b.Navigation("SalaryDeduction");
                });
#pragma warning restore 612, 618
        }
    }
}
