//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CURD_UsingDB_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpTbl()
        {
            this.DeptTbls = new HashSet<DeptTbl>();
        }
    
        public long EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<long> DeptId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeptTbl> DeptTbls { get; set; }
        public virtual DeptTbl DeptTbl { get; set; }
    }
}
