// <auto-generated />
using CurdApiEx.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurdApiEx.Migrations
{
    [DbContext(typeof(CustContext))]
    [Migration("20240710052630_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurdApiEx.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1L,
                            Address = "Nigdi",
                            CreditLimit = 8000m,
                            CustomerName = "Rajesh",
                            EmailID = "rajesh@hotmail.com"
                        },
                        new
                        {
                            CustomerID = 2L,
                            Address = "Akurdi",
                            CreditLimit = 12000m,
                            CustomerName = "Suresh",
                            EmailID = "suresh@gmailmail.com"
                        },
                        new
                        {
                            CustomerID = 3L,
                            Address = "Pimpri",
                            CreditLimit = 15000m,
                            CustomerName = "Ramesh",
                            EmailID = "ramesh@hotmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
