//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEx18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTbl
    {
        public CategoryTbl()
        {
            this.ProductTbls = new HashSet<ProductTbl>();
        }
    
        public long CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<ProductTbl> ProductTbls { get; set; }
    }
}
