// <auto-generated />
using ApiCurdEx.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCurdEx.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241213142902_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiCurdEx.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerTbl");

                    b.HasData(
                        new
                        {
                            CustomerID = 1L,
                            Address = "Nigdi",
                            CreditLimit = 15000m,
                            CustomerName = "Ramesh",
                            EmailAddress = "ramesh@gmail.com",
                            MobileNo = "98765403"
                        },
                        new
                        {
                            CustomerID = 2L,
                            Address = "Akurdi",
                            CreditLimit = 13000m,
                            CustomerName = "Sham",
                            EmailAddress = "sham@gmail.com",
                            MobileNo = "99765403"
                        },
                        new
                        {
                            CustomerID = 3L,
                            Address = "Wakad",
                            CreditLimit = 10000m,
                            CustomerName = "Raju",
                            EmailAddress = "raju@gmail.com",
                            MobileNo = "98765483"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
