// <auto-generated />
using ApiAssignmentEX.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAssignmentEX.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiAssignmentEX.Models.Dept", b =>
                {
                    b.Property<long>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeptID"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptID");

                    b.ToTable("DeptTbl");

                    b.HasData(
                        new
                        {
                            DeptID = 1L,
                            DeptName = "Computer"
                        },
                        new
                        {
                            DeptID = 2L,
                            DeptName = "Production"
                        },
                        new
                        {
                            DeptID = 3L,
                            DeptName = "Purchase"
                        },
                        new
                        {
                            DeptID = 4L,
                            DeptName = "Sales"
                        });
                });

            modelBuilder.Entity("ApiAssignmentEX.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpID"));

                    b.Property<long>("DeptID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpID");

                    b.HasIndex("DeptID");

                    b.ToTable("EmpTbl");

                    b.HasData(
                        new
                        {
                            EmpID = 1L,
                            DeptID = 1L,
                            EmpName = "Sham",
                            Salary = 30000m
                        },
                        new
                        {
                            EmpID = 2L,
                            DeptID = 4L,
                            EmpName = "Ramesh",
                            Salary = 78000m
                        },
                        new
                        {
                            EmpID = 3L,
                            DeptID = 1L,
                            EmpName = "Suresh",
                            Salary = 39000m
                        },
                        new
                        {
                            EmpID = 4L,
                            DeptID = 2L,
                            EmpName = "Arun",
                            Salary = 18000m
                        },
                        new
                        {
                            EmpID = 5L,
                            DeptID = 3L,
                            EmpName = "Raj",
                            Salary = 45000m
                        });
                });

            modelBuilder.Entity("ApiAssignmentEX.Models.Emp", b =>
                {
                    b.HasOne("ApiAssignmentEX.Models.Dept", "Depts")
                        .WithMany()
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depts");
                });
#pragma warning restore 612, 618
        }
    }
}
