//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstEx12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdTbl
    {
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string MfgName { get; set; }
        public decimal Price { get; set; }
        public long CategoryID { get; set; }
    
        public virtual CatTbl CatTbl { get; set; }
    }
}
