// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using corecurdEx.Models;

#nullable disable

namespace corecurdEx.Migrations
{
    [DbContext(typeof(CustContext))]
    [Migration("20240703084851_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("corecurdEx.Models.Area", b =>
                {
                    b.Property<long>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AreaID"));

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaID");

                    b.ToTable("AreaTbl");

                    b.HasData(
                        new
                        {
                            AreaID = 1L,
                            AreaName = "Pimpri"
                        },
                        new
                        {
                            AreaID = 2L,
                            AreaName = "Nigdi"
                        },
                        new
                        {
                            AreaID = 3L,
                            AreaName = "Akurdi"
                        },
                        new
                        {
                            AreaID = 4L,
                            AreaName = "Ravet"
                        });
                });

            modelBuilder.Entity("corecurdEx.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"));

                    b.Property<long>("AreaID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.HasIndex("AreaID")
                        .IsUnique();

                    b.ToTable("CustomerTbl");
                });

            modelBuilder.Entity("corecurdEx.Models.Customer", b =>
                {
                    b.HasOne("corecurdEx.Models.Area", "Area")
                        .WithOne("Customer")
                        .HasForeignKey("corecurdEx.Models.Customer", "AreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("corecurdEx.Models.Area", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
