//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurdOpUsingDBFirstEx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaTbl
    {
        public AreaTbl()
        {
            this.CustomerTbls = new HashSet<CustomerTbl>();
        }
    
        public long AreaID { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<CustomerTbl> CustomerTbls { get; set; }
    }
}
