//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurdOpUsingDBFirstEx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTbl
    {
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string EmailID { get; set; }
        public decimal CreditLimit { get; set; }
        public long AreaID { get; set; }
    
        public virtual AreaTbl AreaTbl { get; set; }
    }
}
