// <auto-generated />
using CurdUsing_6Version.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurdUsing_6Version.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20240618035957_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurdUsing_6Version.Models.Dept", b =>
                {
                    b.Property<long>("DeptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeptID"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptID");

                    b.ToTable("DeptTbl");

                    b.HasData(
                        new
                        {
                            DeptID = 1L,
                            DeptName = "Computer"
                        },
                        new
                        {
                            DeptID = 2L,
                            DeptName = "HR"
                        },
                        new
                        {
                            DeptID = 3L,
                            DeptName = "Process"
                        });
                });

            modelBuilder.Entity("CurdUsing_6Version.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DeptID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpID");

                    b.HasIndex("DeptID");

                    b.ToTable("EmpTbl");

                    b.HasData(
                        new
                        {
                            EmpID = 1L,
                            Address = "Akurdi",
                            DeptID = 2L,
                            EmailID = "suresh@gmail.com",
                            EmpName = "Suresh",
                            Salary = 23000m
                        },
                        new
                        {
                            EmpID = 2L,
                            Address = "Pimpri",
                            DeptID = 3L,
                            EmailID = "manish@hotmail.com",
                            EmpName = "Manish",
                            Salary = 27000m
                        },
                        new
                        {
                            EmpID = 3L,
                            Address = "Nigdi",
                            DeptID = 1L,
                            EmailID = "raj@gmail.com",
                            EmpName = "Raj",
                            Salary = 33000m
                        });
                });

            modelBuilder.Entity("CurdUsing_6Version.Models.Emp", b =>
                {
                    b.HasOne("CurdUsing_6Version.Models.Dept", "Department")
                        .WithMany("Emps")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CurdUsing_6Version.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
