//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFIRST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTbl
    {
        public long EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmailId { get; set; }
        public decimal Salary { get; set; }
        public long DeptId { get; set; }
    
        public virtual DeptTbl DeptTbl { get; set; }
    }
}
