// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VIewCompEx.Models;

#nullable disable

namespace VIewCompEx.Migrations
{
    [DbContext(typeof(VContext))]
    [Migration("20240718092934_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VIewCompEx.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpID"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpID");

                    b.ToTable("Emps");

                    b.HasData(
                        new
                        {
                            EmpID = 1L,
                            DeptName = "Computer",
                            EmpName = "Sunil",
                            Salary = 34000m
                        },
                        new
                        {
                            EmpID = 2L,
                            DeptName = "Sales",
                            EmpName = "Ramesh",
                            Salary = 67000m
                        },
                        new
                        {
                            EmpID = 3L,
                            DeptName = "Purchase",
                            EmpName = "Vilas",
                            Salary = 51000m
                        },
                        new
                        {
                            EmpID = 4L,
                            DeptName = "Production",
                            EmpName = "Vikas",
                            Salary = 23000m
                        });
                });

            modelBuilder.Entity("VIewCompEx.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("MfgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            MfgName = "Intex",
                            Price = 450m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 2L,
                            MfgName = "Mi",
                            Price = 780m,
                            ProductName = "Charger"
                        },
                        new
                        {
                            ProductID = 3L,
                            MfgName = "Dell",
                            Price = 1450m,
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            ProductID = 4L,
                            MfgName = "Seggate",
                            Price = 4450m,
                            ProductName = "HardDisk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
