// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewCompEx.Models;

#nullable disable

namespace ViewCompEx.Migrations
{
    [DbContext(typeof(VContext))]
    partial class VContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViewCompEx.Models.Book", b =>
                {
                    b.Property<long>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookID"));

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1L,
                            AuthorName = "Pune Board",
                            BookName = "BalBharti",
                            Price = 88m
                        },
                        new
                        {
                            BookID = 2L,
                            AuthorName = "Pune Board",
                            BookName = "Geometry",
                            Price = 170m
                        });
                });

            modelBuilder.Entity("ViewCompEx.Models.Emp", b =>
                {
                    b.Property<long>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmpID"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpID");

                    b.ToTable("Emps");

                    b.HasData(
                        new
                        {
                            EmpID = 1L,
                            DeptName = "Computer",
                            EmpName = "Ramesh",
                            Salary = 34000m
                        },
                        new
                        {
                            EmpID = 2L,
                            DeptName = "Sales",
                            EmpName = "Sunil",
                            Salary = 54000m
                        },
                        new
                        {
                            EmpID = 3L,
                            DeptName = "Sales",
                            EmpName = "Raj",
                            Salary = 70000m
                        },
                        new
                        {
                            EmpID = 4L,
                            DeptName = "Computer",
                            EmpName = "Sham",
                            Salary = 75000m
                        });
                });

            modelBuilder.Entity("ViewCompEx.Models.Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("MfgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1L,
                            MfgName = "Dell",
                            Price = 670m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductID = 2L,
                            MfgName = "Intex",
                            Price = 1230m,
                            ProductName = "KeyBoard"
                        },
                        new
                        {
                            ProductID = 3L,
                            MfgName = "LG",
                            Price = 8990m,
                            ProductName = "Monitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
