//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckBox_MVC_Ex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckBox_MVCEntities : DbContext
    {
        public CheckBox_MVCEntities()
            : base("name=CheckBox_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColorTbl> ColorTbls { get; set; }
        public virtual DbSet<ProductColorTbl> ProductColorTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
    }
}
